### ISSUE TITLE
TASM support?

### ISSUE THREAD

**Issue by Heath123** [mborik/z80-macroasm-vscode#13]
TASM seems like quite a popular assembler, and the tutorial that I'm following uses it. It isn't listed on the list of compatible assemblers, though - would it be hard to add?

**Comment by Heath123** [comment]
Also this isn't to do with this extension, but should I switch to something else like SjASMPlus? The tutorial (for programming assembly for TI calculators) does seem quite old

**Comment by mborik** [comment]
@Heath123 Hi, honestly I've never heard about TASM for Z80, I thought that it's old x86 assembler from Borland.
Oh, I see, you mean that Telemark assembler, 23 years old, running from DOS? I'm googling it for couple of minutes to find some documentation and syntax description (so I wouldn't say it's popular. 😁 ) but I think that syntax is pretty compatible with current macro-assemblers (which I strongly recommend to use instead of that abandoned DOS thing!) so you still could use my VSCode extension - basically, it's independed from assembler you use.

**Comment by Heath123** [comment]
Ah, I did try SjASMPlus but the syntax is completely different, I'll try some other ones though probably

**Comment by mborik** [comment]
@Heath123, let me repeat what I said above: **z80-macroasm** VSCode extension is **completelly independent** from assembler what you use. Basic syntax and mnemonics of Z80 is same everywhere so I don't know what is an aspect which prevent you from the using this extension with ANY assembler (more specifically you don't mention your issue).

**Comment by Heath123** [comment]
Well nothing seems to work (for example Go To Definition doesn't work and there's no built-in problem matcher)

**Comment by Heath123** [comment]
Wait, Go To Definition does work, never mind (and I can make my own problem matcher)
File indexing doesn't seem to be fully working though, as I can't go to things defined in another file (edit: Wait, I can, but only sometimes)

**Comment by mborik** [comment]
Okay, but problem matchers are just a "bonus" included in this extension. It's more or less collaborative thing when some users sent me their own problem matchers of their favourite macroassemblers to include it into z80-macroasm extension. In general, everyone could define his own problem matcher in `tasks.json` where you declare your own build process - it's pretty simple with VSCode documentation.
Second thing, read the documentation: In general (for performance sake) z80-macroasm takes into account just **included files from current file** you have opened. So, if your assembler doesn't have `include` (or if you including your files different way) you should look for `z80-macroasm.seekSymbolsThroughWorkspace` option in Settings to enable crawling through all files in your workspace. [See documentation »»](https://github.com/mborik/z80-macroasm-vscode#%EF%B8%8F-settings)

**Comment by Heath123** [comment]
I did enable that, but it's missing some symbols from a file but not others. I guess I'll make another issue or PR if I can find out why

**Comment by mborik** [comment]
It's not necessary to create new issue. Describe here your issue, specifically, whole scope of problem, screenshots, I'm not the Oracle. 🤓
I convinced the problem is only with your configuration..
