### ISSUE TITLE
Colons within quotes are replace by a new line

### ISSUE THREAD

**Issue by vmorilla** [mborik/z80-macroasm-vscode#14]
I have a piece of code like this:

```asm
  DEFM: "Don't break : please"
```

The formatter will replace by invalid code like this:
```asm
  DEFM    "Don't break
  please"
```

**Comment by vmorilla** [comment]
In order to avoid the problem, I've started using  "z80-macroasm.format.splitInstructionsByColon": false in my settings.

**Comment by mborik** [comment]
😲 
Ugh, it's very nasty bug that should be fixed. Thank you for your report!
_Sorry for my late answer but github stop sending me notifications of this project._ 😒
