### ISSUE TITLE
Work with other file types

### ISSUE THREAD

**Issue by nockieboy** [mborik/z80-macroasm-vscode#15]
I have tried every permutation possible (or so it seems) to get this package to recognise the assembler file extensions I'm using - .Z80.  For some reason, it refuses to code-highlight or otherwise work with my Z80 assembly files with the .Z80 extension.  I've saved the exact same file as a .ASM file and it works fine with that.  I've edited the settings and added .Z80 into the 'Files: include' array (**/*.{z80,asm,inc,s}) and have edited the JSON directly, but to no avail.

Any suggestions?

**Comment by mborik** [comment]
You probably should just set a proper association in your global or workspace [`settings.json`](https://github.com/mborik/z80-macroasm-vscode/wiki/settings.json). All relevant options was described that wiki page but you should look for `"files.associations"` section.
Let me know if it's working.

**Comment by nockieboy** [comment]
Ah - thanks for the link to [`settings.json`](https://github.com/mborik/z80-macroasm-vscode/wiki/settings.json). Was able to get the settings working after seeing that example.  I wasn't setting 'files.associations', just 'files.include', which was causing my issue.

Thanks for the quick reply! :)

**Comment by nockieboy** [comment]
Issue resolved.
