### ISSUE TITLE
sjasm module name is deleted on save 

### ISSUE THREAD

**Issue by bereal** [mborik/z80-macroasm-vscode#16]
Hello and thanks for the great plugin!

I am having issues with saving files when I use sjasmplus `module` construct, the module name is erased:

Before saving:

        MODULE name
        ;; code
        ENDMODULE

After saving:

        MODULE
        ;; formatted code
        ENDMODULE

Using version 0.7.1, vscode 1.55.2

**Comment by mborik** [comment]
Sorry for that. Yes, I honestly admit that whole formatter was released slightly premature and not well tested. I'm developing it alone and I'm out of time in testing of that features and behaviour.
So, in next few days will be all formatter functionality disabled by default in update. Sorry for all these nasty issues. 😞

**Comment by bereal** [comment]
@mborik hey, no problem at all, I can live without modules for now or will find a workaround. Your plugin is already very useful as it is :)

**Comment by mborik** [comment]
> @mborik hey, no problem at all, I can live without modules for now or will find a workaround.

No no no, you shouldn't find workaround in your code, just disable intrusive formatting in your VSCode's `settings.json` by adding:
```json
"[z80-macroasm]": {
  "editor.formatOnType": false,
  "editor.formatOnSave": false,
},
```
