### ISSUE TITLE
highlighting missed for ends (end of structure) directive from sjasmplus  

### ISSUE THREAD

**Issue by dlancer** [mborik/z80-macroasm-vscode#17]
highlighting missed for **ends** (end of structure) directive from sjasmplus .

Example:

```asm
  struct point
x db 0
y db 0    
  ends

```

Result (0.7.1):

![image](https://user-images.githubusercontent.com/145080/117465852-89037a00-af6b-11eb-9643-6da6ea9ad000.png)

**Comment by mborik** [comment]
Thank you for your report and screenshot.
Sure, `ends` will be added to syntax highlighter and all keyword processors.
