### ISSUE TITLE
[REQ] Could you add this extension to the Open VSX Registry?

### ISSUE THREAD

**Issue by niel** [mborik/z80-macroasm-vscode#19]
As the title says. Some versions of Code, distributed on Linux in particular, use [Open VSX Registry](https://open-vsx.org/) instead of the Microsoft Markeplace.

**Comment by mborik** [comment]
Sure, I see no problem with this. 👍

**Comment by niel** [comment]
Many thanks

**Comment by mborik** [comment]
Published on OpenVSX:
https://open-vsx.org/extension/mborik/z80-macroasm

_(I'm waiting for approval a verification of my publishing namespace)_

**Comment by niel** [comment]
Many thanks.
