### ISSUE TITLE
splitInstructionsByColon: false doesn't work properly

### ISSUE THREAD

**Issue by kolnogorov** [mborik/z80-macroasm-vscode#22]
I am the guy who writes many instruction in one line, separated by colon, so, i need to have `splitInstructionsByColon` set to `false`.

But eventually, when it's set to false, you just can't write space symbol after colon (because it's trimmed), so it's impossible to type more than one instruction in a line:

https://user-images.githubusercontent.com/8288103/145063054-d453859b-5fa7-4750-8d03-9978adf2636c.mp4

**Comment by kolnogorov** [comment]
I made a PR that fix it: https://github.com/mborik/z80-macroasm-vscode/pull/23

But really i am not sure, is it a proper bugfix or just a workaround.

**Comment by kolnogorov** [comment]
Tested it in a last few days and found some bugs with inserting tabs and spaces before line if it begins with label.
I am not sure, if it was affected by my fix or it was beforehand, so i will test it more deeply and report the results.

**Comment by mborik** [comment]
@kolnogorov I've done some massive refactor to improve experience while on-type formatting and completion.
Multi-instruction behaviour on line was tested to work pretty well. I hope that will be much better.

**Comment by kolnogorov** [comment]
@mborik so it will be in the next version, and this issue can be closed? :)

**Comment by mborik** [comment]
Closing by releasing of [v0.7.8](https://github.com/mborik/z80-macroasm-vscode/releases/tag/v0.7.8)
