### ISSUE TITLE
Format on-type incorrectly trims expressions.

### ISSUE THREAD

**Issue by anrikun** [mborik/z80-macroasm-vscode#25]
Type:
`ld a,0xC0+2`
Then type Space.
Result: +2 gets deleted.
`ld a,0xC0`

**Comment by mborik** [comment]
Sorry for late response. My GitHub notifications was full of my corporate messages so this unfortunately slipped my attention. I'll check that, it's critical for Formatter enabled.

**Comment by anrikun** [comment]
Thank you @mborik!

**Comment by mborik** [comment]
Hi @anrikun, version [v0.7.9](https://github.com/mborik/z80-macroasm-vscode/releases/tag/v0.7.9) which I just released should fixing your issue. Please, let me know if it works for you. 😉

**Comment by anrikun** [comment]
Thank you @mborik! I'll test it this weekend and let you know :smile:

**Comment by anrikun** [comment]
@mborik 
I don't know if I'm doing something wrong but enabling format has no effect whatsoever :open_mouth: 
It has an effect in v0.7.8 but no longer both in v0.7.9 and v0.7.10.

**Comment by mborik** [comment]
Can you describe your issue more specifically? What is you configuration, some steps to reproduce...?

https://github.com/mborik/z80-macroasm-vscode/assets/1952738/f85680e3-f906-4985-8e5f-a1e28803f5bf
