### ISSUE TITLE
M80 accepts `$` in identifiers/labels

### ISSUE THREAD

**Issue by ravn** [mborik/z80-macroasm-vscode#27]
I have some old Z80 sources that I wrote for the M80 assembler.

As M80 accepts $-signs in labels I used those, but those are not correctly identified here.  My guess would be that this line

          "match": "\\b([a-zA-Z][\\w\\.]+)\\b",

should be changed to

          "match": "\\b([a-zA-Z][\\w\\.$]+)\\b",

(see https://github.com/mborik/z80-macroasm-vscode/blob/ec54f202298c0c3ed41a237ccb546c740afd86b4/syntaxes/z80-macroasm.tmLanguage.json#L297 )

but I am not experienced with writing extensions so would first see if it was an easy fix for a maintainer.

**Comment by ravn** [comment]
One of my old files showing this: https://github.com/ravn/rc702-bios/blob/master/QUEUE.MAC

**Comment by mborik** [comment]
Sorry, but I think that it will be much easier to change your label naming (especially if it f.e. some legacy code) than to introduce discrepancy into syntax highlighter that could lead to unexpected results.
