### ISSUE TITLE
Allow to disable asm auto-completion

### ISSUE THREAD

**Issue by Dark-Schneider-666** [mborik/z80-macroasm-vscode#29]
Hi,

I feel this plug-in almost perfect but for the asm auto-completion, IMHO very intrusive. The asm language is "short" to write, the completion boxes appearing so frequently for short writes can be distracting, and sometimes you have to press even more keys, i.e. when writing "ret", have to press enter 2 times for going to the next line.
Then I see very useful the auto-completion of labels, but not so much for the asm code itself. If I could disable it I'd do.

Thanks for the plug-in to all this.

**Comment by theNestruo** [comment]
Hi,

I think the same about auto-completion in assembly, but it can be solved with language-specific configuration in the user settings (`settings.json`):
```json
"[z80-macroasm]": {
	"editor.quickSuggestions": {
		"comments": "off",
		"strings": "off",
		"other": "off"
	},
},
```

Note: I also have this two settings in general (i.e.: for any language). I think they are not relevant, but, just in case...:
```json
"editor.suggestOnTriggerCharacters": false,
"editor.wordBasedSuggestions": false,
```

**Comment by Dark-Schneider-666** [comment]
Hello,
Tried but the auto-completion is still there even after reload.

**Comment by mborik** [comment]
Hi @Dark-Schneider-666,
thank you for your very good and relevant suggestion. Honestly, last 2 months I've been doing a demo for FOReVER demoparty (and it won!!! 🤩) and I was seriously pi**ed off with my own extension for exactly same reason. So, when I manage to finish my current WIP projects in next few weeks I will implement such configuration options to disable suggests on something, like us, who are highly skilled in Z80 don't need. 👍

**Comment by mborik** [comment]
Hi @Dark-Schneider-666, version [v0.7.9](https://github.com/mborik/z80-macroasm-vscode/releases/tag/v0.7.9) which I just released should not suggest instructions by default. Please, let me know if it improve your experience. 😉

**Comment by anrikun** [comment]
Nice suggestion and addition @Dark-Schneider-666 @mborik! I'll test it this weekend as well.

**Comment by ssg** [comment]
I just hit that problem yesterday when I wanted to give the extension a spin. It's especially problematic when you write `ld hl,` and autocomplete appears but you habitually press space, and it completes it to `ld hl,a`. Quite annoying. Let me give the new version a try as well. :)

**Comment by ssg** [comment]
It seems like I have the latest version and still hit that problem despite "Suggest On Instructions" is disabled. I guess I need "argument suggestions" to be turned off too.

**Comment by ssg** [comment]
@theNestruo's `"editor.suggestOnTriggerCharacters": false` setting recommendation fixed that problem for me.

**Comment by Dark-Schneider-666** [comment]
> @theNestruo's `"editor.suggestOnTriggerCharacters": false` setting recommendation fixed that problem for me.

Nice. As I had it installed from earlier it was not set by default even if uninstalled and reinstalled as VSCode saves the config and didn't know where it saves on macOS (have to find).

**Comment by mborik** [comment]
> I just hit that problem yesterday when I wanted to give the extension a spin. It's especially problematic when you write `ld hl,` and autocomplete appears but you habitually press space, and it completes it to `ld hl,a`. Quite annoying. Let me give the new version a try as well. :) 

Ah, I see! Thank you for this specific case description. I think that issue is, that one of commit characters for instructions and arguments completion is **space**. I think that could lead to these problems. This would be easy to fix. ☝️

**Comment by mborik** [comment]
Hi guys, especially @ssg, check [latest release](https://github.com/mborik/z80-macroasm-vscode/releases/tag/v0.7.10), please, where I removed space key as commit character for suggestions.

**Comment by ssg** [comment]
sorry @mborik, many things have come up at the same time, so I couldn't check it yet. I'll comment here if it repros in the latest version. thanks!
