### ISSUE TITLE
Opening of included file

### ISSUE THREAD

**Issue by rgiot** [mborik/z80-macroasm-vscode#3]
It would be nice if it was possible to open (in a new tab) included files by using a key shortcut when the cursor is on an `include` line directive (or equivalent) or by CTRL-clicking on the filename.

**Comment by mborik** [comment]
great idea, will be implemented 👍

**Comment by mborik** [comment]
solved in 6044c7f, released as [v0.5.0](/mborik/z80-macroasm-vscode/releases/tag/v0.5.0)
