### ISSUE TITLE
Respect editor settings

### ISSUE THREAD

**Issue by obiwanjacobi** [mborik/z80-macroasm-vscode#4]
Do you check the editor settings (.vscode)?
Seems like the asm editor is inserting tabs instead of spaces as my editor settings say...

Other than that, excellent extension!

**Comment by mborik** [comment]
VSCode language extensions doesn't affect an editor settings in any way.
VSCode has three levels: User settings, Workspace settings and Folder settings. Each "closest" settings to your source file replaces that global and user settings, so, please, check your settings (`Ctrl+','`)

**Comment by obiwanjacobi** [comment]
Curious: I have a `settings.json` in the `.vscode` folder that says `"editor.insertSpaces": true`.
Still when I Tab I do not get spaces... (also have `"editor.renderWhitespace": "all"` so I can see)
(Language mode of the `.asm` file is set to `Z80 Macro-Assembler`)

**Comment by mborik** [comment]
Check also status line at the bottom-right edge of the editor where should be detected/set whitespace formatting of current file, eg.: `Spaces: 4 | LF`

**Comment by obiwanjacobi** [comment]
Yep, looks good. Funny thing is all other editor windows (.c/.cmd/.json) work fine/as expected..?
`Convert Indentation to Spaces` does not work either...?

**Comment by mborik** [comment]
Sorry, but definitely this couldn't be an issue of language extension. Described behavior is very strange and I suggest you to try clean install of VSCode and different source code.

**Comment by obiwanjacobi** [comment]
Fair enough. Thanx.

**Comment by mborik** [comment]
fixed in c6ecd90, released in v0.5.0
