### ISSUE TITLE
Definition not found

### ISSUE THREAD

**Issue by maziac** [mborik/z80-macroasm-vscode#5]
Local labels are not always found. E.g.

![Bildschirmfoto 2019-03-10 um 11 55 02](https://user-images.githubusercontent.com/3081973/54083989-62197100-432b-11e9-9130-272058e4527c.jpg)

The label .l12 is defined locally but it is not found via g1.l12.

**Comment by mborik** [comment]
sorry, now I'm in time press, I will start with bugfixing the extension next week.

**Comment by maziac** [comment]
Hi,

I'm just reaching out to you to inform you that I copied part of your (i.e. Imanolea's) extension
to my extension asm-code-lens.
It was the part with the syntax highlighting.
The license is MIT so I guess it's OK. Anyhow I wanted to let you know also to check if my acknowledgements to your code are fine with you.
You find it at the end of the Readme.md here:
https://github.com/maziac/asm-code-lens

**Comment by mborik** [comment]
No problem maziac, it's nature of open-source projects and I'm so glad that you choose my humble project which I started as my own very simple handy tool. I looking forward to test your extension, it looks great! 😉
